
 pid_flag: true
 thruster12ratio: 1.07
 pid_maxforce: 0.05
 base_force: 0.1
 external_K_yaw : 0.1
 external_Td_yaw : 0.0
 external_Ti_yaw : 200.0
 external_e_yaw_differential : 0.0
 external_e_yaw_integral : 0.0
 external_e_yaw_last : 0.0
 external_e_yaw : 0.0
 external_out_yaw : 0.0 
 external_dout_yaw : 0.0
 external_dout_pre_yaw : 0.0
 external_e_yaw_integral_a : 0.2


 internal_K_yaw : 0.25
 internal_Td_yaw : 0.1
 internal_Ti_yaw : 400.0
 internal_e_yaw_differential : 0.0
 internal_e_yaw_integral : 0.0
 internal_e_yaw_last : 0.0
 internal_e_yaw : 0.0 
 internal_out_yaw : 0.0
 internal_dout_yaw : 0.0
 internal_dout_pre_yaw : 0.0
 internal_e_yaw_integral_a : 0.3

 desired_yaw : 0.0
