# Params
roboat_filter:

  # # GPS covariance params
  # minGPSCovTh: 0.000001
  # maxGPSCovTh: 0.9

  # Dual Beacon params
  hedge_ref_pos_cov: 0.0004      #reference position covariance value (based on documentation, error is 0.02 so variance approx 0.02^2)
  hedge_ref_acc_cov: 0.000001    #reference linear acceleration covariance value (when not computed)
  hedge_ref_gyr_cov: 0.000001    #reference angular velocity covariance value (when not computed)
  hedge_ref_compass_cov: 0.07    #reference compasss orientation covariance value (based on data, error is 15deg so variance (15*pi/180)^2)
  
  # The beacon antennas are -45 degrees off from the x axis:
  #
  #  beacon
  #    |  9.0cm
  #    |
  #   centre --------------------- centre
  #                   18 cm          |
  #                                  | 9.0cm
  #                                 beacon
  # 
  dualhedge_heading_offset: 135             #(deg)
  
  
  # Dual GPS params
  # headingOffset: 15  # Hand tuned to align point cloud with earth. This is a combination of the gps offset and cloud offset.
  # gpsBaseline: 3.66

