# -----------------------------------------------------------------------------
# SWARM SETTINGS
# -----------------------------------------------------------------------------
# ids of the boats composing the swarm
update_rate: 30.0           #(Hz)
distance_till_update: 0.05  #(m)
path_length: 100.0          #(s), duration of the path plotted 