# -----------------------------------------------------------------------------
# SWARM SETTINGS
# -----------------------------------------------------------------------------
# ids of the boats composing the swarm
update_rate: 30  #(Hz)
distance_till_update: 0.05  #(m)
